ALTER TABLE clients ADD COLUMN street VARCHAR(255) DEFAULT NULL;
ALTER TABLE clients ADD COLUMN zip VARCHAR(20) DEFAULT NULL;
ALTER TABLE clients ADD COLUMN city VARCHAR(100) DEFAULT NULL;
ALTER TABLE clients ADD COLUMN email VARCHAR(255) DEFAULT NULL;
ALTER TABLE clients ADD COLUMN phone VARCHAR(50) DEFAULT NULL;
ALTER TABLE clients ADD COLUMN website VARCHAR(255) DEFAULT NULL;
